export const affiliateMap = {
	'intelligence artificielle': 'https://amzn.to/votre-lien-ia',
	processeur: 'https://amzn.to/votre-lien-cpu',
	logiciel: 'https://votre-lien-saas.com',
};
// https://youtube.com/shorts/L1ZM1gd_mUg?si=nn1gdH6ZINE7iXa7

export const topics = [
	// --- TECH, IA & DATA (Le cœur de Phénix) ---
	'IA générative',
	'Modèles LLM et NLP',
	'Agents IA autonomes',
	'Model Context Protocol (MCP)',
	'Automatisation et Workflows',
	'Prompt Engineering',
	'IA et Éthique',
	'Informatique Quantique',
	'Robotique et Humanoïdes',
	'Technologie et Futur',
	'Technologie et Innovation',
	'Nouvelles technologies et IA',
	'Vision par Ordinateur (Computer Vision)',
	'Intelligence Artificielle Générale (AGI)',
	'IA et Reconnaissance Vocale',
	"Edge AI (IA sur l'appareil)",
	'Mégadonnées (Big Data) et Analytics',
	'Data Science et Algorithmes',
	'Entraînement des modèles et GPU',
	'IA Low-resource et Small Language Models',

	// --- DÉVELOPPEMENT & ARCHITECTURE LOGICIELLE ---
	'Web Développeur',
	'Architecture Microservices',
	'DevOps et CI/CD',
	'Bases de données Edge et Cloud',
	'Frameworks JavaScript & TypeScript',
	'Développement Mobile',
	'Open Source Ecosystem',
	'Low-Code et No-Code',
	'API Design et GraphQL',
	"Développement d'applications SaaS",
	'WebAssembly (Wasm)',
	'Serverless Architecture',
	'Clean Code et Refactoring',
	'Tests automatisés et QA',
	'UI/UX Design pour Développeurs',
	'Conteneurisation (Docker, Kubernetes)',
	"Développement d'extensions et plugins",
	'Gestion de la dette technique',

	// --- CYBERSÉCURITÉ, RÉSEAUX & INFRASTRUCTURE ---
	'Cybersécurité 2026',
	'Cryptographie et Blockchain',
	'Hacking Éthique',
	'Protection des Données',
	'Réseaux 5G et 6G',
	'Cloud Security',
	'Architecture Zero Trust',
	'Ransomwares et Menaces étatiques',
	'Sécurité des objets connectés (IoT)',
	'Identité numérique et Authentification',
	'Gouvernance des données et RGPD',
	'Filtres anti-spam et Sécurité Emails',

	// --- ENGINES, GAMING & METAVERSE ---
	'Gaming et Divertissement',
	'Moteurs de Jeux et Rendu',
	'Réalité Virtuelle et Augmentée',
	'Esport et Compétition',
	'Culture Pop et Divertissement',
	'Cinéma et Séries',
	'Streaming et Médias',
	'Cloud Gaming',
	'Intelligence Artificielle dans les Jeux',
	'Modding et Communautés de joueurs',
	'Récit interactif et Game Design',
	'Consoles de nouvelle génération',

	// --- FINANCE, CRYPTO, MONÉTISATION & SAAS ---
	'Économie et Business',
	'Économie et Marchés',
	'Finance et Cryptomonnaies',
	'Finance et Investissement',
	'SaaS et Web Monetization',
	'Innovation et Startups',
	'E-commerce et RetailTech',
	'Growth Hacking',
	'Capital Risque et Levées de fonds',
	'Web3 et Applications Décentralisées (dApps)',
	'Finance Décentralisée (DeFi)',
	'Monnaies Numériques de Banque Centrale (MNBC)',
	'Trading algorithmique et Bots',
	'Solopreneuriat et Side-Hustles',
	"Modèles d'abonnement et Économie numérique",
	'Bourse et Marchés financiers',

	// --- SCIENCES, ESPACE & PHYSIQUE ---
	'Actualité Scientifique',
	'Science et Découvertes',
	'Espace et Exploration',
	'Astronomie et Astrophysique',
	'Physique Quantique',
	'Fusion Nucléaire',
	'Exoplanètes et Vie extraterrestre',
	'Missions martiennes',
	'Satellites et Débris spatiaux',
	'Nanotechnologies',
	'Matériaux du futur (Graphène, etc.)',
	'Neurobiologie',

	// --- ENVIRONNEMENT, ÉNERGIE, GREEN & CLIMAT ---
	'Environnement et Énergie',
	'Environnement et Climat',
	'Énergies Renouvelables',
	'Technologies Vertes (Greentech)',
	'Décarbonation',
	'Biodiversité et Conservation',
	'Alimentation et Agriculture',
	'Agrotech et Foodtech',
	"Gestion de l'eau et Recyclage",
	'Villes durables et Smart Cities',
	'Économie circulaire',
	'Transition énergétique',
	"Stockage de l'énergie et Batteries",
	'Agriculture verticale et Hydroponie',

	// --- SANTÉ, BIOTECH & BIEN-ÊTRE ---
	'Santé et Biotechnologie',
	'Santé et Bien-être',
	'Biohacking',
	'Longévité et Génétique',
	'MedTech et E-santé',
	'Neurosciences',
	'Édition génomique (CRISPR)',
	'Prothèses et Bionique',
	'Santé mentale et Télémédecine',
	'Sommeil et Rythmes circadiens',
	'Nutrition et Microbiome',
	'Épidémiologie et Prévention',

	// --- MOBILITÉ, TRANSPORTS & LOGISTIQUE ---
	'Mobilité et Transports',
	'Véhicules Autonomes',
	'Automobile Électrique',
	'Aéronautique du Futur',
	'Logistique et Supply Chain',
	'Drones et Livraison autonome',
	'Trains à grande vitesse et Hyperloop',
	'Micro-mobilité (Trottinettes, Vélo électrique)',
	'Exploration sous-marine',
	'Transports maritimes écologiques',

	// --- GÉOPOLITIQUE, SOCIÉTÉ & DROIT ---
	'Culture et Société',
	'Politique et Géopolitique',
	'Politique et Société',
	'Histoire et Culture',
	'Histoire et Patrimoine',
	'Philosophie et Société',
	'Philosophie et Réflexion',
	'Droit et Éthique',
	'Droit et Justice',
	'Langues et Communication',
	'Éducation et Apprentissage',
	'EdTech et E-learning',
	'Souveraineté numérique',
	"Régulation de l'Internet",
	'Démographie et Migrations',
	'Guerre informationnelle et Fake News',
	"Droit d'auteur et Propriété intellectuelle",

	// --- DESIGN, ART & CRÉATIVITÉ DIGITAL ---
	'Art et Créativité',
	'Musique et Technologie',
	'Design Graphique et UI/UX',
	'Mode et Lifestyle',
	'Architecture et Urbanisme',
	'Art généré par IA',
	'NFT et Propriété numérique',
	'Production musicale assistée par ordinateur',
	'Photographie numérique et Retouche',
	'Typographie et Identité visuelle',

	// --- PRODUCTIVITÉ, PSYCHOLOGIE & TRAVAIL ---
	'Psychologie et Comportement',
	'Psychologie et Développement Personnel',
	'Productivité et Mental',
	'Futur du Travail (Remote, IA)',
	'Gestion du temps et Deep Work',
	"Syndrome de l'épuisement (Burnout) professionnel",
	'Entrepreneuriat et Leadership',
	'No-code pour la productivité',
	'Management à distance',

	// --- HISTOIRE, LOISIRS & EVASION ---
	'Voyages et Tourisme',
	'Voyages et Aventure',
	'Sport et Technologie',
	'Sport et Performance',
	'Nutrition et Fitness',
	'Alpinisme et Exploration extrême',
	'Histoire ancienne et Archéologie',
	'Éco-tourisme',
	'Gastronomie et Arts culinaires',
	'Jeux de société et Stratégie',

];